### PR TITLE
init project

### PR DESCRIPTION
**Pull request by TDM1911**
## Related Tickets:
 
* [#29982](https://edu-redmine.sun-asterisk.vn/issues/29982)
 
## WHAT this PR does?
 
* Init Laravel Framework (ver 7.x)
 
## Notes Impacted Areas:
 
* N/A. 
 
## Attachments:
 
* N/A.

### CODE REVIEW

**Comment by TDM1911** [comment]
ready

**Comment by TDM1911** [comment]
ready

**Comment by TDM1911** [comment]
ready

**Comment by TDM1911** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
thêm file template_PR nhé. Xin Quang nhé.

**Comment by TDM1911** [comment]
ready

**Pull request merged**
